//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication19.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disp
    {
        public int id { get; set; }
        public string UName { get; set; }
        public string Username { get; set; }
        public string Usergmail { get; set; }
        public string MoNumber { get; set; }
        public string UPassword { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
